create database darkwater_fins;
use darkwater_fins;

create table users (
	user_id int primary key,
    user_name varchar(40) not null,
    user_img_url varchar(250),
    email varchar(50) not null,
    passwords varchar(100) not null,
    address varchar(250),
    phone_number varchar(11),
    roles boolean default 0
);

create table Aquarium_Fishs (
	fish_id int primary key,
    fish_name varchar(50) not null,
    fish_img_url varchar(250) not null,
    fish_price float not null,
    fish_sub varchar(100),
    fish_description text,
    fish_stock int default 0,
    fish_category varchar(40),
    purchases int default 0
);


INSERT INTO Aquarium_Fishs (fish_id, fish_name, fish_img_url, fish_price, fish_sub, fish_description, fish_stock, fish_category, purchases) 
VALUES (1, 'Siamese Fighting Fish, White', 'https://i.imgur.com/fQou4dN.jpg', 10.99, 'Known for its striking white color and aggressive nature, often a favorite for its elegance.', 'The Siamese Fighting Fish, or Betta splendens, is a species well known for its vivid colors and elaborate fins. Among the various colorations, the White Siamese Fighting Fish stands out for its immaculate, snow-like appearance. These fish are native to the rice paddies, floodplains, and canals of Thailand and neighboring Southeast Asian countries. The species has been selectively bred for its aggressive behavior towards other males, making it famous among aquarium enthusiasts.
White Siamese Fighting Fish are characterized by their pristine white coloration, which gives them a pure and elegant look. This variety is relatively rare, and its beauty lies in its simplicity. Unlike more colorful Betta varieties, the White Siamese Fighting Fish exudes a serene and sophisticated aura. Despite their calm appearance, these fish possess a fierce territorial instinct, which is a hallmark of the Betta species. Males are known for their aggressive displays, which include flaring their gill covers and spreading their fins to appear larger. In their natural habitat, Siamese Fighting Fish are adapted to survive in low-oxygen environments due to their specialized labyrinth organ. This organ allows them to breathe atmospheric air, enabling them to thrive in stagnant waters where other fish might struggle. This adaptation has contributed to their success as a species and their popularity in the aquarium trade
Caring for a White Siamese Fighting Fish requires a suitable tank environment that mimics their natural habitat. A tank with plenty of hiding spots, such as plants, rocks, and caves, is ideal. These fish prefer slightly acidic to neutral water with a temperature range of 75 to 80 degrees Fahrenheit. Regular water changes and proper filtration are essential to maintain the water quality, as Betta fish are sensitive to poor water conditions. Feeding a White Siamese Fighting Fish is relatively straightforward. They are carnivorous and thrive on a diet of high-quality Betta pellets, supplemented with live or frozen foods such as bloodworms, brine shrimp, and daphnia. Its important to avoid overfeeding, as Betta fish can be prone to obesity and related health issues.
One of the most fascinating aspects of the White Siamese Fighting Fish is their breeding behavior. Males construct bubble nests at the water surface, using saliva-coated air bubbles. When a female is ready to spawn, the male wraps around her, and as she releases eggs, he fertilizes them. The male then collects the eggs in his mouth and places them in the bubble nest, where he guards them until they hatch. This nurturing behavior is quite remarkable, especially given the male otherwise aggressive nature.
The White Siamese Fighting Fish elegance and grace, combined with its fiery spirit, make it a captivating addition to any home aquarium. Observing their behavior, from flaring their fins in a display of dominance to constructing bubble nests, offers endless fascination for aquarists. These bubble nests, built by males using saliva-coated air bubbles, are a key part of their breeding process. When a female lays eggs, the male carefully places them in the nest and guards them until they hatch.', 230, 'Unique', 1000),
(2, 'Milk Cow Betta Fish', 'https://i.imgur.com/cBZRE2S.jpg', 12.24, 'Features a unique black and white pattern resembling a milk cow, adding a distinctive touch.', 'The Milk Cow Betta Fish is a unique and visually striking variety of Betta fish, characterized by its distinctive black and white pattern reminiscent of a Holstein cow. This beautiful contrast makes it a popular choice among Betta enthusiasts. The pattern varies with each individual, ensuring that no two Milk Cow Bettas are exactly alike. These fish possess the same labyrinth organ as other Betta species, allowing them to breathe atmospheric air, which makes them highly adaptable to different water conditions.
In addition to their striking appearance, Milk Cow Betta Fish are known for their hardy nature, making them a suitable choice for beginners and experienced aquarists alike. Their active and inquisitive behavior provides endless entertainment, making them a delightful pet to watch and care for
Caring for a Milk Cow Betta Fish involves creating a suitable tank environment that mimics their natural habitat. A tank with plenty of hiding spots, such as plants, rocks, and caves, is ideal. These fish prefer slightly acidic to neutral water with a temperature range of 75 to 80 degrees Fahrenheit. Regular water changes and proper filtration are essential to maintain the water quality, as Betta fish are sensitive to poor water conditions.
Feeding a Milk Cow Betta Fish is relatively straightforward. They are carnivorous and thrive on a diet of high-quality Betta pellets, supplemented with live or frozen foods such as bloodworms, brine shrimp, and daphnia. Its important to avoid overfeeding, as Betta fish can be prone to obesity and related health issues.
In summary, the Milk Cow Betta Fish is a magnificent example of Betta splendens, combining beauty and fierceness in a single package. Their care requires attention to detail and a commitment to maintaining optimal water conditions, but the reward is a strikingly beautiful and endlessly fascinating pet.
Dumbo Pineapple Betta Fish, The Dumbo Pineapple Betta Fish is an extraordinary variety that captivates observers with its unique combination of features. Named for its oversized pectoral fins that resemble the ears of Disney Dumbo, this Betta fish is a visual delight. The Pineapple variant is characterized by its vibrant yellow body with a gradient of colors that often includes shades of orange and red, reminiscent of a ripe pineapple. These fish are not only visually appealing but also relatively easy to care for, making them a popular choice for aquarists. Their large, flowing fins add to their gracefulness as they swim, creating a beautiful display in any aquarium. Despite their delicate appearance, Dumbo Pineapple Bettas are quite hardy and can thrive in a variety of water conditions. Their unique blend of features and striking coloration make them a standout addition to any Betta collection.', 120, 'Unique', 200), 
(3, 'Dumbo Pineapple Betta Fish', 'https://i.imgur.com/f6dgYqI.png', 5.23, 'Characterized by large, "dumbo-style" fins and a vibrant yellow color, resembling a pineapple.',
'The Dumbo Pineapple Betta Fish is an extraordinary variety that captivates observers with its unique combination of features. Named for its oversized pectoral fins that resemble the ears of Disney Dumbo, this Betta fish is a visual delight. The Pineapple variant is characterized by its vibrant yellow body with a gradient of colors that often includes shades of orange and red, reminiscent of a ripe pineapple. These fish are not only visually appealing but also relatively easy to care for, making them a popular choice for aquarists. Their large, flowing fins add to their gracefulness as they swim, creating a beautiful display in any aquarium. Despite their delicate appearance, Dumbo Pineapple Bettas are quite hardy and can thrive in a variety of water conditions. Their unique blend of features and striking coloration make them a standout addition to any Betta collection.', 121, 'Unique', 150),
(4, 'Fluorescent Betta Fish', 'https://i.imgur.com/zkLqL37.jpg', 45.67, 'Glow under UV light, offering bright, neon colors like green, pink, or orange.', 'Fluorescent Betta Fish, also known as GloFish Bettas, are a genetically modified variety of Betta fish that have been engineered to exhibit vibrant, glowing colors under certain lighting conditions. These fish are available in a range of neon colors, including green, red, orange, blue, and purple, making them a visually stunning addition to any aquarium. The fluorescence is achieved through the introduction of genes from jellyfish or coral, resulting in fish that glow brightly under blacklight or blue LED lights. Fluorescent Betta Fish are just as hardy and easy to care for as their non-modified counterparts, requiring similar tank conditions and diet. Their glowing appearance adds a unique and captivating element to any aquarium setup, making them a favorite among aquarists looking to add a touch of neon brilliance to their collection.', 231, 'Color Variants', 252), 
(5, 'Wild Thai Betta Fish', 'https://i.imgur.com/Igt8Hd4.jpg', 88.10, 'A wild variation with natural colors,reflecting its natural habitat.', 'Wild Thai Betta Fish, or Betta mahachaiensis, are a species of Betta fish native to the mangroves and swamps of Thailand. Unlike their more flamboyant relatives, Wild Thai Bettas have a more subdued coloration, typically featuring earthy tones of green, brown, and blue. These fish are prized by enthusiasts for their natural beauty and resilience, as they are well adapted to surviving in the harsh conditions of their native habitats. Wild Thai Bettas are known for their strong territorial instincts and unique breeding behaviors, including the construction of intricate bubble nests. Keeping Wild Thai Bettas in an aquarium requires a setup that mimics their natural environment, with plenty of hiding places and vegetation. Their fascinating behavior and natural appearance make them a rewarding species for dedicated Betta keepers.', 127, 'Unique', 263), 
(6, 'Nemo Galaxy Betta Fish', 'https://i.imgur.com/WjIX4Is.png', 12.35, 'Combining bright orange hues with star-like specks, resembling the famous Nemo fish.', 'The Nemo Galaxy Betta Fish is a stunning and colorful variety known for its vibrant orange, blue, and black patterns that resemble the beloved clownfish from the movie "Finding Nemo." These fish often have a marbled appearance, with each individual displaying a unique combination of colors and patterns. The "Galaxy" aspect refers to the iridescent specks and patches that give the fish a celestial, starry appearance. Nemo Galaxy Bettas are highly sought after by collectors for their unique and eye-catching beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their playful and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 100, 'Color Variants', 231),
(7, 'Halfmoon Betta Fish', 'https://i.imgur.com/FgZQ2sH.jpg', 100.12, 'Known for its large, wide tail that forms a perfect half-moon shape.', 'Halfmoon Betta Fish are named for their spectacularly large, 180-degree spread tail that resembles a half-moon. This variety is highly prized in the Betta community for its stunning and symmetrical appearance. The tail can come in a wide range of colors and patterns, making each Halfmoon Betta a unique and beautiful specimen. These fish are known for their dramatic displays, often flaring their fins to assert dominance or attract a mate. Halfmoon Bettas require careful attention to water quality and tank conditions to ensure their delicate fins remain in pristine condition. Despite their regal appearance, they are relatively easy to care for and can thrive in a well-maintained aquarium. Their striking beauty and impressive fin displays make them a popular choice among Betta enthusiasts.', 243, 'Tail', 450),
(8, 'Red Fancy Star Betta Fish', 'https://i.imgur.com/XuVuUgM.jpg', 87.32, 'Features a vibrant red color with unique star-like patterns on its fins and body.', 'The Red Fancy Star Betta Fish is a dazzling variety known for its bright red coloration and intricate patterns that resemble a starry night sky. These fish often have a mix of red, white, and blue hues, creating a stunning and unique appearance. The "Fancy Star" aspect refers to the iridescent spots and specks that adorn their bodies, giving them a sparkling, celestial look. Red Fancy Star Bettas are highly sought after by collectors and hobbyists for their unique and captivating beauty. They are relatively easy to care for and require similar tank conditions and diet as other Betta varieties. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 120, 'Dragon', 234), 
(9, 'Green Dragon Betta Fish', 'https://i.imgur.com/jsUBACS.jpg', 90.23, 'Displays metallic green scales with a striking dragon-like appearance.', 'Green Dragon Betta Fish are a striking and exotic variety known for their vivid green coloration and dragon-like scales. These fish have a unique appearance, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Green Dragon Bettas are highly prized by collectors for their rare and captivating beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 150, 'Dragon', 124), 
(10, 'Black Dragon Betta Fish', 'https://i.imgur.com/fPBPuN2.png', 18.54, 'Features deep black hues with a metallic shine, creating a dramatic look.', 'Black Dragon Betta Fish are an incredibly striking variety known for their deep black coloration and dragon-like scales. These fish have a unique appearance, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Black Dragon Bettas are highly prized by collectors for their rare and captivating beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 111, 'Dragon', 324), 
(11, 'Golden Dragon Betta Fish', 'https://i.imgur.com/bpdA5JR.jpg', 99.10, 'A dazzling golden color with metallic scales, resembling a mythical dragon.', 'Golden Dragon Betta Fish are a magnificent and exotic variety known for their shimmering golden scales and dragon-like appearance. These fish have a unique and captivating look, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Golden Dragon Bettas are highly prized by collectors for their rare and stunning beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 102, 'Dragon', 237),
(12, 'Red Dragon Betta Fish', 'https://i.imgur.com/pXJsALL.png', 8.99, 'Known for its bold red color with metallic sheen, resembling a dragon fiery appearance.', 'Red Dragon Betta Fish are a stunning and exotic variety known for their vibrant red coloration and dragon-like scales. These fish have a unique appearance, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Red Dragon Bettas are highly prized by collectors for their rare and captivating beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 7, 'Dragon', 110), 
(13, 'Koi Betta Fish', 'https://i.imgur.com/cWSIkUQ.jpg', 500.99, 'Has a similar color pattern to Koi fish, with a mix of red, white, and black spots.', 'The Koi Betta Fish is one of the most colorful and visually striking varieties of Betta. Inspired by the Japanese koi carp, this Betta exhibits a unique color pattern that resembles the bright and vibrant colors of the koi fish. Their bodies typically have a mix of white, orange, black, and red hues, creating a dazzling, multi-colored effect. Koi Bettas are admired for their beautiful and varied coloration, making them a popular choice for those seeking a Betta with an exotic look. These fish are not only known for their beauty but also for their feisty and territorial nature, which is common among male Bettas.', 220, 'Color Variants', 528),
(14, 'Galaxy Betta Fish', 'https://i.imgur.com/PVePSXL.jpg', 2.99, 'Known for its starry pattern, the body often glitters with small white dots that resemble a galaxy.', 'The Galaxy Betta is an eye-catching fish with a remarkable appearance that often features bright, speckled patterns reminiscent of stars in a galaxy. The body of a Galaxy Betta is usually dark, such as black or deep blue, while its fins may be dotted with speckles of white or other bright colors. These Betta fish are known for their vibrant color contrast and celestial-like appearance. As with other Betta fish, males are territorial and should be housed separately. The Galaxy Betta is prized for its stunning and unique look, and it stands out as a striking addition to any aquarium.', 5, 'Color Variants', 90),
(15, 'Veil Tail Betta Fish', 'https://i.imgur.com/gztLG5n.png', 1000.00, 'Characterized by long, flowing fins that create a veil-like effect as it swims.', 'The Veil Tail Betta Fish is one of the most classic and recognizable varieties of Betta, known for its long, flowing tail that forms a veil-like shape when fully extended. This fish often comes in a variety of colors, including shades of red, blue, and purple, with their flowing tails adding an extra element of elegance. Veil Tails are popular in the Betta community due to their beauty and graceful movements. However, their long tails can be prone to damage, requiring extra care in tank setup to prevent harm. Males, as usual, should be housed alone due to their territorial nature.', 20, 'Tail', 900), 
(16, 'Double Tail Betta Fish', 'https://i.imgur.com/fZcqL7F.jpg', 5.99, 'Features two distinct tails, offering a unique and elegant appearance.', 'The Double Tail Betta is an extraordinary fish, prized for its two distinct tails, which are the result of a genetic mutation. This unique feature gives the fish a symmetrical and balanced appearance, with two separate, flowing tails extending from the body. Double Tail Bettas are typically larger than their single-tail counterparts, with wider and more elaborate fins. These Bettas are known for their aggressive nature, particularly males who will often display territorial behavior. The Double Tail Bettas impressive tail structure and dynamic presence make it a favorite among those who appreciate both beauty and boldness in their aquatic pets.', 213, 'Tail', 154), 
(17, 'Delta Betta Fish', 'https://i.imgur.com/Ugu97fz.jpg', 73.99, 'Has a wide, triangular-shaped tail, resembling the Greek letter delta.', 'The Delta Betta Fish is named for the triangular shape of its tail, which spreads outward like the Greek letter "Delta." This unique tail shape gives the fish a striking, symmetrical appearance that is admired by Betta enthusiasts. Delta Bettas come in a wide range of colors, including vibrant reds, blues, and purples, and their tails are often long and gracefully tapered. These Bettas are known for their calm demeanor compared to other Betta species, although males are still territorial. Their distinctive tail and elegant coloration make the Delta Betta a sought-after species for those looking for beauty and style in their aquariums.', 193, 'Tail', 302), 
(18, 'Super Delta Betta Fish', 'https://i.imgur.com/rB7KCni.jpg', 36.79, 'Similar to the Delta Betta but with an even wider, more pronounced tail.', 'The Super Delta Betta Fish is a larger and more dramatic version of the Delta Betta, with an even more exaggerated tail that can spread up to 130 degrees, giving it a bold, sweeping appearance. These Bettas are known for their impressive, large fins and symmetrical tail shape, which often appears like a grand fan when fully flared. Super Delta Bettas are available in a variety of colors, from deep reds to vibrant blues. While they share the territorial nature of other Betta fish, their striking tails and calm demeanor make them an attractive choice for Betta collectors looking for a fish with both grace and bold beauty.', 232, 'Tail', 212),
(19, 'Crescent Tail Betta Fish', 'https://i.imgur.com/feuLHLI.jpg', 19.99, 'Known for its crescent-shaped tail, creating a flowing, elegant look in the water.', 'The Crescent Tail Betta Fish is known for its distinctive tail shape, which resembles a crescent moon when fully extended. This unique tail structure is characterized by a rounded, semi-circular shape that gives the fish an elegant and flowing look. Crescent Tail Bettas often come in bright and bold colors, including vibrant reds, blues, and purples. Their graceful, rounded tails allow them to glide effortlessly through the water, making them a mesmerizing sight in any aquarium. Like other Betta species, males can be territorial and aggressive toward each other, so it is important to house them alone. The Crescent Tail Betta is a beautiful and enchanting variety that adds charm to any tank.', 62, 'Tail', 569);


create table Fish_Foods (
	fishFood_id int primary key,
    fishFood_name varchar(50) not null,
    fishFood_img_url varchar(250) not null,
    fishFood_price float not null,
    fishFood_sub varchar(100),
    fishFood_description text,
    fishFood_stock int default 0,
    fishFood_category varchar(40),
    purchases int default 0
);


INSERT INTO Fish_Foods (fishFood_id, fishFood_name, fishFood_img_url, fishFood_price, fishFood_sub, fishFood_description, fishFood_stock, fishFood_category, purchases)
VALUES 
(1, 'API Betta Food', 'https://i.imgur.com/uePdyIl.jpg', 6.99, 'Formulated to enhance Betta fish colors and support overall health.', 'API Betta Food is an essential product specially designed to enhance the colors and health of Betta fish. This food is crafted using high-quality ingredients to ensure that Betta fish receive the necessary nutrients for their overall health and well-being. The primary goal of this product is to promote vibrant coloration, making the Betta fish look more stunning and alive in the aquarium. It provides a balanced mix of proteins, vitamins, and minerals, helping Betta fish stay strong and active. API Betta Food also supports immune health, reducing the risk of disease and ensuring that Betta fish thrive in their environment. The small, easily digestible pellets are specifically tailored to the unique needs of Betta fish, encouraging easy consumption. This product is ideal for any Betta fish owner who desires to maintain a healthy and beautiful fish that shows off its true colors. Whether used for daily feeding or as part of a balanced diet, API Betta Food guarantees optimal nutrition, promoting overall health, and enhancing the Bettas appearance.', 120, 'Betta Food', 47),
(2, 'New Life Spectrum Betta 70', 'https://i.imgur.com/9t7jO78.jpg', 12.99, 'High-quality pellets that improve Betta fish color, growth, and vitality.', 'New Life Spectrum Betta 70 is a high-quality food that is specifically designed to improve the growth, color, and vitality of Betta fish. These nutrient-rich pellets are made with premium ingredients, ensuring that the Betta fish get all the essential nutrients needed for a long and healthy life. The formula includes a blend of proteins, vitamins, and omega-3 fatty acids, which helps to boost the Bettas immune system and support healthy growth. With a focus on both health and color enhancement, New Life Spectrum Betta 70 encourages vibrant coloration while promoting the Betta’s overall well-being. Additionally, the pellets are highly digestible, which ensures that the fish can efficiently absorb all the nutrients, leading to improved vitality. This product is perfect for Betta fish owners who want to provide their fish with the best nutrition available. It supports the natural beauty of the Betta fish and ensures that they remain strong, active, and healthy.', 80, 'Betta Food', 190),
(3, 'TetraBetta', 'https://i.imgur.com/0TNt6XE.jpg', 4.99,'Well-balanced food that helps Betta fish thrive, supporting health and vibrant colors.', 'TetraBetta is a well-balanced Betta food that provides the essential nutrients Betta fish need to thrive in an aquarium. This specially formulated food enhances the fishs coloration and promotes healthy growth, making Betta fish more vibrant and active. TetraBetta is enriched with a balanced combination of proteins, vitamins, and minerals, which support the immune system, improve digestion, and promote overall health. The small pellet size is perfect for Betta fish to eat easily, ensuring they consume the right amount of food. The formula is designed to support the specific dietary needs of Betta fish, helping them to maintain strong immunity and resist diseases. The food also contributes to the bright colors Betta fish are known for, ensuring that they stay visually stunning throughout their lives. Whether used as a daily meal or as a supplement, TetraBetta is a reliable choice for Betta fish owners who want to ensure their fish have the best nutrition for health and beauty.', 200, 'Betta Food', 894),
(4, 'Aqueon PURE Betta', 'https://i.imgur.com/IBQQeKD.jpg', 5.49, 'Nutrient-rich food that promotes vibrant color and well-being in Betta fish.', 'Aqueon PURE Betta food is a premium product created to promote the vibrant color and overall health of Betta fish. This nutrient-rich food is made with high-quality ingredients that support long-term well-being, growth, and vitality. Aqueon PURE Betta food contains a special blend of fishmeal and proteins, making it highly digestible and perfect for Betta fish. The food is also packed with essential vitamins and minerals, which help to boost the immune system, support healthy skin and scales, and maintain good digestive health. This food is formulated to bring out the natural colors of Betta fish while keeping them active and strong. Betta fish owners will appreciate the benefits of Aqueon PURE Betta food, as it provides a well-rounded diet that ensures their fish are healthy, beautiful, and energetic. Aqueon PURE Betta is perfect for everyday feeding, offering Betta fish the necessary nutrients for a thriving and colorful life.', 150, 'Betta Food', 264),
(5, 'New Life Spectrum Betta 25g (Naturox Series)', 'https://i.imgur.com/yFsuDaS.jpg', 11.99, 'Premium food with antioxidant-rich ingredients for optimal Betta fish nutrition.', 'New Life Spectrum Betta 25g (Naturox Series) is a top-tier Betta food that boasts antioxidant-rich ingredients for superior Betta fish nutrition. The formula includes a blend of natural ingredients designed to boost Betta fish health and improve their coloration. The food is enhanced with vitamins and omega-3 fatty acids, promoting overall wellness, immune strength, and vitality. Betta fish owners will appreciate the high quality of this product, which helps ensure their fish thrive and maintain their natural beauty.', 60, 'Betta Food', 574),
(6, 'HIKARI Betta Revive.8', 'https://i.imgur.com/TioDsna.jpg', 7.99, 'Improves Betta fish health and brings out natural color with high-quality ingredients.', 'HIKARI Betta Revive.8 is a specialized fish food that improves Betta fish health while bringing out the natural colors. The high-quality ingredients in this product are designed to provide Betta fish with all the essential nutrients for optimal health and growth. This food enhances color development by providing Betta fish with proteins, vitamins, and minerals that support immune strength and vitality. The formula also helps improve digestive health, ensuring that Betta fish absorb all the nutrients efficiently. Betta Revive.8 also promotes overall wellness, reducing the risk of disease and ensuring that the Betta fish remains active, healthy, and vibrant. This food is ideal for Betta fish owners who want to provide their fish with the best nutrition, promoting both their beauty and health. HIKARI Betta Revive.8 helps keep Betta fish at their best, ensuring that they stay strong, resilient, and colorful in any aquarium.', 100, 'Betta Food', 375),
(7, 'Penn Plax PBV1 7', 'https://i.imgur.com/65wejBk.jpg', 5.99, 'Balanced food with essential vitamins and minerals to support Betta fish health.', 'Penn Plax PBV1 7 is a high-quality, balanced food that is specifically designed to meet the needs of Betta fish. This food contains a mix of essential vitamins, minerals, and proteins that promote the growth, coloration, and health of Betta fish. The formula is easy to digest, ensuring that Betta fish can efficiently absorb all the nutrients provided in each pellet. Penn Plax PBV1 7 helps enhance the Betta fish’s immune system, making them more resistant to diseases. The food supports healthy digestion, which is essential for Betta fish to maintain their energy and vitality. With its balanced formula, this food ensures that Betta fish owners can provide the best possible nutrition for their fish, keeping them strong, vibrant, and healthy. Penn Plax PBV1 7 is an excellent choice for anyone looking to keep their Betta fish in top condition.', 90, 'Cichlid Food', 247),
(8, 'Betta Minerals 4', 'https://i.imgur.com/JLhi4gY.jpg', 8.49, 'Mineral-enriched food that supports health and provides essential nutrients for Betta fish.', 'Betta Minerals 4 is a mineral-enriched food designed to support the health and vitality of Betta fish. This food is specifically formulated to enhance the Betta fish’s coloration while providing essential nutrients that promote strong immunity and overall health. The unique blend of minerals, vitamins, and proteins in Betta Minerals 4 ensures that the Betta fish receive all the nutrition they need for a long and healthy life. The food is easily digestible, allowing the fish to absorb all the necessary nutrients without difficulty. Betta Minerals 4 also supports healthy growth and enhances the Betta fish’s natural colors, making them more vibrant and visually stunning. This product is ideal for Betta fish owners who want to provide their fish with the best possible nutrition to ensure they are healthy, active, and full of color.', 110, 'Betta Food', 533),
(9, 'Fritz Aquatics Betta Botanicals', 'https://i.imgur.com/jEXfvpW.jpg', 6.29, 'Botanically-enriched food that enhances color and provides health benefits for Betta fish.', ' Fritz Aquatics Betta Botanicals is a premium, botanically-enriched food designed to improve the health and appearance of Betta fish. This specialized formula combines the power of natural botanicals with high-quality ingredients, providing a unique blend of nutrients to enhance both coloration and vitality. The botanical ingredients in this food offer numerous health benefits, including immune system support and improved digestion, ensuring that Betta fish stay healthy and strong. The food is also designed to encourage vibrant, rich colors by supplying essential minerals and vitamins that promote the natural pigments of Betta fish. In addition to supporting coloration, Betta Botanicals also helps to bring out the Bettas natural behavior, keeping the fish active and engaged. Fritz Aquatics Betta Botanicals is perfect for Betta fish owners who want to provide their pets with a well-rounded, nutritious diet that boosts health and enhances beauty. With its easy-to-digest formula and natural ingredients, this food is an excellent choice for promoting the long-term well-being of Betta fish.', 79, 'Betta Food', 112),
(10, 'DreamDealsSG 200', 'https://i.imgur.com/S6CsWkm.jpg', 9.99, 'Premium Betta food that offers a balanced diet, supporting growth, color, and health.', 'DreamDealsSG 200 is a premium Betta food that offers a balanced diet to support healthy growth, coloration, and overall well-being of Betta fish. This high-quality food is specifically designed to meet the nutritional needs of Betta fish, providing a blend of proteins, vitamins, and minerals that promote vibrant colors and strong immune systems. The carefully crafted formula supports both the health and beauty of Betta fish by improving their coloration, promoting healthy skin, and helping them develop strong, robust bodies. The small pellets are highly digestible, making it easy for Betta fish to consume and absorb the nutrients efficiently. DreamDealsSG 200 also enhances the Betta fish’s natural energy, keeping them active and lively. This food is perfect for Betta fish owners who want to maintain the overall health of their fish while encouraging their natural beauty and vibrant colors. By providing this balanced and nutrient-dense food, Betta fish owners can ensure that their pets lead a long, healthy, and colorful life.', 34, 'Cichlid Food', 46),
(11, 'Blue Ridge', 'https://i.imgur.com/IiQtzn1.jpg', 7.49, 'Specially formulated food that enhances the vibrant colors and health of Betta fish.', 'Blue Ridge is a specially formulated food designed to enhance the vibrant colors and overall health of Betta fish. This premium fish food provides a balanced combination of essential nutrients that promote healthy growth, coloration, and vitality. Blue Ridge includes high-quality proteins, vitamins, and minerals that help to boost the immune system, support the development of Betta fish, and improve their overall health. The food is rich in nutrients that promote vibrant coloration, ensuring that Betta fish retain their beauty and vibrant hues. In addition to enhancing color, Blue Ridge helps to support healthy digestion, which allows Betta fish to absorb the necessary nutrients more efficiently. With its easy-to-digest formula, Blue Ridge ensures that Betta fish get the maximum benefit from each meal. This food is ideal for Betta fish owners who want to provide their fish with a high-quality diet that supports both health and beauty. Blue Ridge helps Betta fish stay strong, healthy, and colorful, making it an excellent choice for any Betta fish enthusiast.', 45, 'Cichlid Food', 143),
(12, 'Aqueon Cichlid Food M', 'https://i.imgur.com/w2yj3nb.jpg', 7.99, 'Designed for Cichlids, providing balanced nutrition with added vitamins and minerals.', 'Aqueon Cichlid Food M is a specially designed food for cichlids, providing a balanced nutrition that supports the health and vitality of these unique fish. This food is made with high-quality ingredients, ensuring that it meets the specific dietary needs of cichlids. It is formulated with a blend of proteins, vitamins, and minerals that promote healthy growth, vibrant coloration, and strong immune systems. The food helps cichlids develop and maintain their beautiful colors while promoting long-term health and vitality. Aqueon Cichlid Food M also supports digestive health, ensuring that cichlids can efficiently absorb the nutrients they need. This food is perfect for both freshwater and saltwater cichlids, making it a versatile and reliable option for fish owners. Whether used as a daily meal or as part of a balanced diet, Aqueon Cichlid Food M guarantees optimal nutrition for cichlids, helping them stay strong, healthy, and vibrant.', 247, 'Cichlid Food', 756),
(13, 'Aqueon PURE Betta', 'https://i.imgur.com/Aj8GkWx.jpg', 5.99, 'High-quality Betta food that promotes vibrant colors and long-term health.', 'Aqueon PURE Betta is a high-quality food designed to support the vibrant color and overall health of Betta fish. This nutrient-rich food provides a balanced combination of proteins, vitamins, and minerals to help Betta fish maintain optimal health and growth. The specially formulated pellets are designed to be easily digestible, ensuring that Betta fish absorb all the essential nutrients. Aqueon PURE Betta helps to promote the natural colors of Betta fish, making them more vibrant and eye-catching. The food is also enriched with vitamins and minerals that support the immune system, helping Betta fish remain healthy and resistant to diseases. Whether used as a daily food or as a supplement to other meals, Aqueon PURE Betta is a great choice for Betta fish owners who want to provide their pets with the best possible nutrition. It ensures that Betta fish stay healthy, active, and beautiful, making it an excellent addition to any aquarium.', 173, 'Betta Food', 291),
(14, 'Aqueon', 'https://i.imgur.com/Lu5XOpv.jpg', 4.99, 'General fish food providing balanced nutrition to support fish health and growth.', ' Aqueon is a general fish food that provides a well-rounded diet to support the overall health and growth of various species of fish. This food is designed to be versatile, catering to a wide range of fish, including tropical and coldwater varieties. The formula is enriched with essential proteins, vitamins, and minerals that promote healthy development, vibrant coloration, and strong immune systems. Aqueon is made with high-quality ingredients that are easy to digest, ensuring that fish can absorb all the nutrients they need. The food also supports digestive health, helping to maintain a clean and healthy aquarium environment. Aqueon is perfect for fish owners who want to provide their fish with balanced, high-quality nutrition. With its affordable price and reliable formula, Aqueon is an excellent choice for a variety of fish, ensuring they grow, thrive, and remain healthy.', 278, 'General Fish Food', 842),
(15, 'Ocean Nutrition Formula', 'https://i.imgur.com/TFPi4C6.jpg', 9.49, 'Versatile fish food supporting balanced diet for various species, enhancing health and color.', 'Ocean Nutrition Formula is a versatile fish food that supports a balanced diet for a variety of fish species, promoting overall health, growth, and vibrant coloration. This high-quality food is formulated with a blend of proteins, vitamins, and minerals that are essential for fish to maintain strong immune systems and healthy development. The pellets are made with high-quality ingredients that ensure efficient digestion, allowing fish to absorb all the nutrients they need. Ocean Nutrition Formula supports the health of both freshwater and saltwater fish, making it a versatile option for aquarium enthusiasts. The formula is designed to enhance color and vitality, ensuring that fish retain their natural beauty and energy. Whether used as a staple food or as part of a diverse diet, Ocean Nutrition Formula is an excellent choice for fish owners looking to provide their fish with the best nutrition for optimal health and appearance.', 47, 'General Fish Food', 461),
(16, 'Glofish betta', 'https://i.imgur.com/KKxdgl0.jpg', 6.99, 'Designed to support Betta fish needs, enhancing colors and vitality.', ' Glofish Betta food is designed specifically to meet the nutritional needs of Betta fish, enhancing their natural beauty and vitality. The food is made with high-quality ingredients that promote the health, growth, and vibrant coloration of Betta fish. The formula includes a mix of proteins, vitamins, and minerals that help to support the Betta’s immune system and promote healthy digestion. Glofish Betta food also contains special ingredients that enhance the natural colors of Betta fish, ensuring they remain bright and vibrant. The small pellet size is easy for Betta fish to consume, ensuring that they get the right amount of food without difficulty. This food is ideal for Betta fish owners who want to keep their fish healthy and beautiful, providing them with a well-balanced diet that supports long-term well-being.', 36, 'Betta Food', 637),
(17, 'Zoo Med Betta Catappa Leaf, Count of 3', 'https://i.imgur.com/59ADC1a.jpg', 3.99, 'Natural leaves that improve Betta fish health by mimicking their natural habitat.', 'Zoo Med Betta Catappa Leaf is a natural product that provides numerous health benefits for Betta fish. These leaves mimic the Betta fish’s natural habitat, offering a more natural environment that promotes healthy behavior and reduces stress. The leaves are rich in natural compounds that support immune function, improve digestive health, and reduce the likelihood of diseases. They also help to improve water quality by releasing tannins that acidify the water, creating a more natural, comfortable environment for Betta fish. The Catappa leaves also enhance coloration, promoting vibrant hues in Betta fish while encouraging healthy growth. Betta fish owners can use Zoo Med Betta Catappa Leaf to provide their fish with a more natural diet, ensuring they thrive and stay healthy in a stress-free environment.', 4, 'Betta Food', 999),
(18, 'Seachem NutriDiet', 'https://i.imgur.com/IhgF4bt.jpg', 8.99, 'Highly digestible food promoting Betta fish growth, coloration, and health.', 'Seachem NutriDiet is a highly digestible fish food designed to promote the growth, coloration, and health of various fish species. This food is specially formulated to meet the needs of both freshwater and saltwater fish, providing them with all the essential nutrients for a balanced diet. The formula is enriched with proteins, vitamins, and minerals that support healthy growth, vibrant coloration, and a strong immune system. Seachem NutriDiet helps to maintain healthy digestion, ensuring that fish can efficiently absorb all the nutrients they need. The food is also designed to improve the overall health and vitality of fish, reducing stress and boosting energy levels. Seachem NutriDiet is a great choice for aquarium owners who want to provide their fish with a high-quality, nutritious diet that supports both their health and beauty.', 2, 'General Fish Food', 850),
(19, 'San Francisco Bay', 'https://i.imgur.com/n0alqVJ.jpg', 5.49, 'High-quality fish food improving health, color, and vitality for various species.', 'San Francisco Bay fish food is a high-quality product designed to improve the health, color, and vitality of various species of fish. This food is made with a blend of premium ingredients that provide fish with all the essential nutrients they need for strong immune systems, healthy growth, and vibrant coloration. The formula includes proteins, vitamins, and minerals that help fish develop robust bodies and retain their natural beauty. San Francisco Bay fish food is also designed to be easily digestible, allowing fish to absorb all the nutrients efficiently. Whether used as a staple food or as part of a diverse diet, San Francisco Bay ensures that fish stay healthy, active, and visually stunning. It is a great option for fish owners looking for high-quality food that supports the long-term well-being of their pets.', 1, 'General Fish Food', 1000);