create database darkwater_fins;
use darkwater_fins;

create table users (
	user_id int primary key,
    user_name varchar(40) not null,
    user_img_url varchar(250),
    email varchar(50) not null,
    passwords varchar(30) not null,
    address varchar(250),
    phone_number varchar(11),
    roles boolean default 0
);

create table Aquarium_Fishs (
	fish_id int primary key,
    fish_name varchar(50) not null,
    fish_img_url varchar(250) not null,
    fish_price float not null,
    fish_sub varchar(100),
    fish_description text,
    fish_stock int default 0,
    fish_category varchar(40),
    purchases int default 0
);


INSERT INTO Aquarium_Fishs (fish_id, fish_name, fish_img_url, fish_price, fish_sub, fish_description, fish_stock, fish_category, purchases) 
VALUES (1, 'Siamese Fighting Fish, White', 'https://i.imgur.com/fQou4dN.jpg', 10.99, 'Known for its striking white color and aggressive nature, often a favorite for its elegance.', 'The Siamese Fighting Fish, or Betta splendens, is a species well known for its vivid colors and elaborate fins. Among the various colorations, the White Siamese Fighting Fish stands out for its immaculate, snow-like appearance. These fish are native to the rice paddies, floodplains, and canals of Thailand and neighboring Southeast Asian countries. The species has been selectively bred for its aggressive behavior towards other males, making it famous among aquarium enthusiasts.
White Siamese Fighting Fish are characterized by their pristine white coloration, which gives them a pure and elegant look. This variety is relatively rare, and its beauty lies in its simplicity. Unlike more colorful Betta varieties, the White Siamese Fighting Fish exudes a serene and sophisticated aura. Despite their calm appearance, these fish possess a fierce territorial instinct, which is a hallmark of the Betta species. Males are known for their aggressive displays, which include flaring their gill covers and spreading their fins to appear larger. In their natural habitat, Siamese Fighting Fish are adapted to survive in low-oxygen environments due to their specialized labyrinth organ. This organ allows them to breathe atmospheric air, enabling them to thrive in stagnant waters where other fish might struggle. This adaptation has contributed to their success as a species and their popularity in the aquarium trade
Caring for a White Siamese Fighting Fish requires a suitable tank environment that mimics their natural habitat. A tank with plenty of hiding spots, such as plants, rocks, and caves, is ideal. These fish prefer slightly acidic to neutral water with a temperature range of 75 to 80 degrees Fahrenheit. Regular water changes and proper filtration are essential to maintain the water quality, as Betta fish are sensitive to poor water conditions. Feeding a White Siamese Fighting Fish is relatively straightforward. They are carnivorous and thrive on a diet of high-quality Betta pellets, supplemented with live or frozen foods such as bloodworms, brine shrimp, and daphnia. Its important to avoid overfeeding, as Betta fish can be prone to obesity and related health issues.
One of the most fascinating aspects of the White Siamese Fighting Fish is their breeding behavior. Males construct bubble nests at the water surface, using saliva-coated air bubbles. When a female is ready to spawn, the male wraps around her, and as she releases eggs, he fertilizes them. The male then collects the eggs in his mouth and places them in the bubble nest, where he guards them until they hatch. This nurturing behavior is quite remarkable, especially given the male otherwise aggressive nature.
The White Siamese Fighting Fish elegance and grace, combined with its fiery spirit, make it a captivating addition to any home aquarium. Observing their behavior, from flaring their fins in a display of dominance to constructing bubble nests, offers endless fascination for aquarists. These bubble nests, built by males using saliva-coated air bubbles, are a key part of their breeding process. When a female lays eggs, the male carefully places them in the nest and guards them until they hatch.', 230, 'Unique', 1000),
(2, 'Milk Cow Betta Fish', 'https://i.imgur.com/cBZRE2S.jpg', 12.24, 'Features a unique black and white pattern resembling a milk cow, adding a distinctive touch.', 'The Milk Cow Betta Fish is a unique and visually striking variety of Betta fish, characterized by its distinctive black and white pattern reminiscent of a Holstein cow. This beautiful contrast makes it a popular choice among Betta enthusiasts. The pattern varies with each individual, ensuring that no two Milk Cow Bettas are exactly alike. These fish possess the same labyrinth organ as other Betta species, allowing them to breathe atmospheric air, which makes them highly adaptable to different water conditions.
In addition to their striking appearance, Milk Cow Betta Fish are known for their hardy nature, making them a suitable choice for beginners and experienced aquarists alike. Their active and inquisitive behavior provides endless entertainment, making them a delightful pet to watch and care for
Caring for a Milk Cow Betta Fish involves creating a suitable tank environment that mimics their natural habitat. A tank with plenty of hiding spots, such as plants, rocks, and caves, is ideal. These fish prefer slightly acidic to neutral water with a temperature range of 75 to 80 degrees Fahrenheit. Regular water changes and proper filtration are essential to maintain the water quality, as Betta fish are sensitive to poor water conditions.
Feeding a Milk Cow Betta Fish is relatively straightforward. They are carnivorous and thrive on a diet of high-quality Betta pellets, supplemented with live or frozen foods such as bloodworms, brine shrimp, and daphnia. Its important to avoid overfeeding, as Betta fish can be prone to obesity and related health issues.
In summary, the Milk Cow Betta Fish is a magnificent example of Betta splendens, combining beauty and fierceness in a single package. Their care requires attention to detail and a commitment to maintaining optimal water conditions, but the reward is a strikingly beautiful and endlessly fascinating pet.
Dumbo Pineapple Betta Fish, The Dumbo Pineapple Betta Fish is an extraordinary variety that captivates observers with its unique combination of features. Named for its oversized pectoral fins that resemble the ears of Disney Dumbo, this Betta fish is a visual delight. The Pineapple variant is characterized by its vibrant yellow body with a gradient of colors that often includes shades of orange and red, reminiscent of a ripe pineapple. These fish are not only visually appealing but also relatively easy to care for, making them a popular choice for aquarists. Their large, flowing fins add to their gracefulness as they swim, creating a beautiful display in any aquarium. Despite their delicate appearance, Dumbo Pineapple Bettas are quite hardy and can thrive in a variety of water conditions. Their unique blend of features and striking coloration make them a standout addition to any Betta collection.', 120, 'Unique', 200), 
(3, 'Dumbo Pineapple Betta Fish', 'https://i.imgur.com/f6dgYqI.png', 5.23, 'Characterized by large, "dumbo-style" fins and a vibrant yellow color, resembling a pineapple.',
'The Dumbo Pineapple Betta Fish is an extraordinary variety that captivates observers with its unique combination of features. Named for its oversized pectoral fins that resemble the ears of Disney Dumbo, this Betta fish is a visual delight. The Pineapple variant is characterized by its vibrant yellow body with a gradient of colors that often includes shades of orange and red, reminiscent of a ripe pineapple. These fish are not only visually appealing but also relatively easy to care for, making them a popular choice for aquarists. Their large, flowing fins add to their gracefulness as they swim, creating a beautiful display in any aquarium. Despite their delicate appearance, Dumbo Pineapple Bettas are quite hardy and can thrive in a variety of water conditions. Their unique blend of features and striking coloration make them a standout addition to any Betta collection.', 121, 'Unique', 150),
(4, 'Fluorescent Betta Fish', 'https://i.imgur.com/zkLqL37.jpg', 45.67, 'Glow under UV light, offering bright, neon colors like green, pink, or orange.', 'Fluorescent Betta Fish, also known as GloFish Bettas, are a genetically modified variety of Betta fish that have been engineered to exhibit vibrant, glowing colors under certain lighting conditions. These fish are available in a range of neon colors, including green, red, orange, blue, and purple, making them a visually stunning addition to any aquarium. The fluorescence is achieved through the introduction of genes from jellyfish or coral, resulting in fish that glow brightly under blacklight or blue LED lights. Fluorescent Betta Fish are just as hardy and easy to care for as their non-modified counterparts, requiring similar tank conditions and diet. Their glowing appearance adds a unique and captivating element to any aquarium setup, making them a favorite among aquarists looking to add a touch of neon brilliance to their collection.', 231, 'Color Variants', 252), 
(5, 'Wild Thai Betta Fish', 'https://i.imgur.com/Igt8Hd4.jpg', 88.10, 'A wild variation with natural colors,reflecting its natural habitat.', 'Wild Thai Betta Fish, or Betta mahachaiensis, are a species of Betta fish native to the mangroves and swamps of Thailand. Unlike their more flamboyant relatives, Wild Thai Bettas have a more subdued coloration, typically featuring earthy tones of green, brown, and blue. These fish are prized by enthusiasts for their natural beauty and resilience, as they are well adapted to surviving in the harsh conditions of their native habitats. Wild Thai Bettas are known for their strong territorial instincts and unique breeding behaviors, including the construction of intricate bubble nests. Keeping Wild Thai Bettas in an aquarium requires a setup that mimics their natural environment, with plenty of hiding places and vegetation. Their fascinating behavior and natural appearance make them a rewarding species for dedicated Betta keepers.', 127, 'Unique', 263), 
(6, 'Nemo Galaxy Betta Fish', 'https://i.imgur.com/WjIX4Is.png', 12.35, 'Combining bright orange hues with star-like specks, resembling the famous Nemo fish.', 'The Nemo Galaxy Betta Fish is a stunning and colorful variety known for its vibrant orange, blue, and black patterns that resemble the beloved clownfish from the movie "Finding Nemo." These fish often have a marbled appearance, with each individual displaying a unique combination of colors and patterns. The "Galaxy" aspect refers to the iridescent specks and patches that give the fish a celestial, starry appearance. Nemo Galaxy Bettas are highly sought after by collectors for their unique and eye-catching beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their playful and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 100, 'Color Variants', 231),
(7, 'Halfmoon Betta Fish', 'https://i.imgur.com/FgZQ2sH.jpg', 100.12, 'Known for its large, wide tail that forms a perfect half-moon shape.', 'Halfmoon Betta Fish are named for their spectacularly large, 180-degree spread tail that resembles a half-moon. This variety is highly prized in the Betta community for its stunning and symmetrical appearance. The tail can come in a wide range of colors and patterns, making each Halfmoon Betta a unique and beautiful specimen. These fish are known for their dramatic displays, often flaring their fins to assert dominance or attract a mate. Halfmoon Bettas require careful attention to water quality and tank conditions to ensure their delicate fins remain in pristine condition. Despite their regal appearance, they are relatively easy to care for and can thrive in a well-maintained aquarium. Their striking beauty and impressive fin displays make them a popular choice among Betta enthusiasts.', 243, 'Tail', 450),
(8, 'Red Fancy Star Betta Fish', 'https://i.imgur.com/XuVuUgM.jpg', 87.32, 'Features a vibrant red color with unique star-like patterns on its fins and body.', 'The Red Fancy Star Betta Fish is a dazzling variety known for its bright red coloration and intricate patterns that resemble a starry night sky. These fish often have a mix of red, white, and blue hues, creating a stunning and unique appearance. The "Fancy Star" aspect refers to the iridescent spots and specks that adorn their bodies, giving them a sparkling, celestial look. Red Fancy Star Bettas are highly sought after by collectors and hobbyists for their unique and captivating beauty. They are relatively easy to care for and require similar tank conditions and diet as other Betta varieties. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 120, 'Dragon', 234), 
(9, 'Green Dragon Betta Fish', 'https://i.imgur.com/jsUBACS.jpg', 90.23, 'Displays metallic green scales with a striking dragon-like appearance.', 'Green Dragon Betta Fish are a striking and exotic variety known for their vivid green coloration and dragon-like scales. These fish have a unique appearance, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Green Dragon Bettas are highly prized by collectors for their rare and captivating beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 150, 'Dragon', 124), 
(10, 'Black Dragon Betta Fish', 'https://i.imgur.com/fPBPuN2.png', 18.54, 'Features deep black hues with a metallic shine, creating a dramatic look.', 'Black Dragon Betta Fish are an incredibly striking variety known for their deep black coloration and dragon-like scales. These fish have a unique appearance, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Black Dragon Bettas are highly prized by collectors for their rare and captivating beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 111, 'Dragon', 324), 
(11, 'Golden Dragon Betta Fish', 'https://i.imgur.com/bpdA5JR.jpg', 99.10, 'A dazzling golden color with metallic scales, resembling a mythical dragon.', 'Golden Dragon Betta Fish are a magnificent and exotic variety known for their shimmering golden scales and dragon-like appearance. These fish have a unique and captivating look, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Golden Dragon Bettas are highly prized by collectors for their rare and stunning beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 102, 'Dragon', 237),
(12, 'Red Dragon Betta Fish', 'https://i.imgur.com/pXJsALL.png', 8.99, 'Known for its bold red color with metallic sheen, resembling a dragon fiery appearance.', 'Red Dragon Betta Fish are a stunning and exotic variety known for their vibrant red coloration and dragon-like scales. These fish have a unique appearance, with their scales often exhibiting a metallic sheen that adds to their allure. The "Dragon" aspect refers to the thick, armor-like scales that cover their bodies, giving them a rugged and powerful look. Red Dragon Bettas are highly prized by collectors for their rare and captivating beauty. They possess the same hardy characteristics as other Betta fish, making them relatively easy to care for. Their active and inquisitive nature makes them a delightful addition to any aquarium, where they can be observed exploring their environment and interacting with their surroundings.', 7, 'Dragon', 110), 
(13, 'Koi Betta Fish', 'https://i.imgur.com/cWSIkUQ.jpg', 500.99, 'Has a similar color pattern to Koi fish, with a mix of red, white, and black spots.', 'The Koi Betta Fish is one of the most colorful and visually striking varieties of Betta. Inspired by the Japanese koi carp, this Betta exhibits a unique color pattern that resembles the bright and vibrant colors of the koi fish. Their bodies typically have a mix of white, orange, black, and red hues, creating a dazzling, multi-colored effect. Koi Bettas are admired for their beautiful and varied coloration, making them a popular choice for those seeking a Betta with an exotic look. These fish are not only known for their beauty but also for their feisty and territorial nature, which is common among male Bettas.', 220, 'Color Variants', 528),
(14, 'Galaxy Betta Fish', 'https://i.imgur.com/PVePSXL.jpg', 2.99, 'Known for its starry pattern, the body often glitters with small white dots that resemble a galaxy.', 'The Galaxy Betta is an eye-catching fish with a remarkable appearance that often features bright, speckled patterns reminiscent of stars in a galaxy. The body of a Galaxy Betta is usually dark, such as black or deep blue, while its fins may be dotted with speckles of white or other bright colors. These Betta fish are known for their vibrant color contrast and celestial-like appearance. As with other Betta fish, males are territorial and should be housed separately. The Galaxy Betta is prized for its stunning and unique look, and it stands out as a striking addition to any aquarium.', 5, 'Color Variants', 90),
(15, 'Veil Tail Betta Fish', 'https://i.imgur.com/gztLG5n.png', 1000.00, 'Characterized by long, flowing fins that create a veil-like effect as it swims.', 'The Veil Tail Betta Fish is one of the most classic and recognizable varieties of Betta, known for its long, flowing tail that forms a veil-like shape when fully extended. This fish often comes in a variety of colors, including shades of red, blue, and purple, with their flowing tails adding an extra element of elegance. Veil Tails are popular in the Betta community due to their beauty and graceful movements. However, their long tails can be prone to damage, requiring extra care in tank setup to prevent harm. Males, as usual, should be housed alone due to their territorial nature.', 20, 'Tail', 900), 
(16, 'Double Tail Betta Fish', 'https://i.imgur.com/fZcqL7F.jpg', 5.99, 'Features two distinct tails, offering a unique and elegant appearance.', 'The Double Tail Betta is an extraordinary fish, prized for its two distinct tails, which are the result of a genetic mutation. This unique feature gives the fish a symmetrical and balanced appearance, with two separate, flowing tails extending from the body. Double Tail Bettas are typically larger than their single-tail counterparts, with wider and more elaborate fins. These Bettas are known for their aggressive nature, particularly males who will often display territorial behavior. The Double Tail Bettas impressive tail structure and dynamic presence make it a favorite among those who appreciate both beauty and boldness in their aquatic pets.', 213, 'Tail', 154), 
(17, 'Delta Betta Fish', 'https://i.imgur.com/Ugu97fz.jpg', 73.99, 'Has a wide, triangular-shaped tail, resembling the Greek letter delta.', 'The Delta Betta Fish is named for the triangular shape of its tail, which spreads outward like the Greek letter "Delta." This unique tail shape gives the fish a striking, symmetrical appearance that is admired by Betta enthusiasts. Delta Bettas come in a wide range of colors, including vibrant reds, blues, and purples, and their tails are often long and gracefully tapered. These Bettas are known for their calm demeanor compared to other Betta species, although males are still territorial. Their distinctive tail and elegant coloration make the Delta Betta a sought-after species for those looking for beauty and style in their aquariums.', 193, 'Tail', 302), 
(18, 'Super Delta Betta Fish', 'https://i.imgur.com/rB7KCni.jpg', 36.79, 'Similar to the Delta Betta but with an even wider, more pronounced tail.', 'The Super Delta Betta Fish is a larger and more dramatic version of the Delta Betta, with an even more exaggerated tail that can spread up to 130 degrees, giving it a bold, sweeping appearance. These Bettas are known for their impressive, large fins and symmetrical tail shape, which often appears like a grand fan when fully flared. Super Delta Bettas are available in a variety of colors, from deep reds to vibrant blues. While they share the territorial nature of other Betta fish, their striking tails and calm demeanor make them an attractive choice for Betta collectors looking for a fish with both grace and bold beauty.', 232, 'Tail', 212),
(19, 'Crescent Tail Betta Fish', 'https://i.imgur.com/feuLHLI.jpg', 19.99, 'Known for its crescent-shaped tail, creating a flowing, elegant look in the water.', 'The Crescent Tail Betta Fish is known for its distinctive tail shape, which resembles a crescent moon when fully extended. This unique tail structure is characterized by a rounded, semi-circular shape that gives the fish an elegant and flowing look. Crescent Tail Bettas often come in bright and bold colors, including vibrant reds, blues, and purples. Their graceful, rounded tails allow them to glide effortlessly through the water, making them a mesmerizing sight in any aquarium. Like other Betta species, males can be territorial and aggressive toward each other, so it is important to house them alone. The Crescent Tail Betta is a beautiful and enchanting variety that adds charm to any tank.', 62, 'Tail', 569);